// src/solution.cpp -- YOURS, and the ONLY thing timed.
//
//     void hpcbench::solve(const Work& w, const Params& p, Result& y);
//
// The clock starts on entry to this function and stops on return. Everything
// else -- process start-up, generating the weights, allocating and zero-filling
// `y`, writing result.bin, digesting it -- happens outside the timed region and
// costs you nothing.
//
// What that means in practice: reading your own representation out of the
// workdir is INSIDE the clock. `w.open(name)` streams it, `w.map(name)` gives
// you the whole file, `w.read_all(name)` slurps it. Choosing between them, and
// choosing how little you need to read at all, is part of the optimisation.
//
// `p.W` is row-major n_genes x k, already generated by the host: there is no
// gen_W in an entry any more. `y.data` is row-major n_cells x k and arrives
// zero-filled. Compute Y = X * W.
//
// The baseline reads the dense matrix the baseline `prepare` wrote and runs the
// textbook triple loop. Both halves are yours to replace.
#include "task.hpp"

#include <cstdint>
#include <vector>

void hpcbench::solve(const Work& w, const Params& p, Result& y) {
  // On the clock: the baseline pays to read 296 MB of dense doubles.
  Reader r = w.open("matrix.bin");
  const std::uint64_t n_cells = r.read_value<std::uint64_t>();
  const std::uint64_t n_genes = r.read_value<std::uint64_t>();
  std::vector<double> X(static_cast<std::size_t>(n_cells * n_genes));
  r.read(X.data(), X.size() * sizeof(double));
  r.close();

  const std::uint64_t k = p.k;
  for (std::uint64_t i = 0; i < n_cells; ++i)
    for (std::uint64_t g = 0; g < n_genes; ++g)
      for (std::uint64_t c = 0; c < k; ++c)
        y.data[i * k + c] += X[i * n_genes + g] * p.W[g * k + c];
}
